dev_dir: ${oc.env:DEV_PATH}

hydra:
  run:
    dir: ${dev_dir}/im2flow2act/experiment/3D_flow_generation/coffee/${now:%Y-%m-%d_%H-%M-%S}

project_name: 3D_flow_generation
debug: False

training:
  num_train_epochs: 3000
  max_train_steps: null
  gradient_accumulation_steps: 1
  gradient_checkpointing: False
  lr_scheduler: "constant"
  lr_warmup_steps: 0
  mixed_precision: "fp32"
  # dataloader 
  batch_size: 20
  num_workers: 4
  shuffle: True
  pin_memory: True
  persistent_workers: True
  drop_last: False
  # ckpt
  ckpt_frequency: 100
  # load_pretrain_weight
  load_pretrain_weight: True

cfg_random_null_text: True
cfg_random_null_text_ratio: 0.1
max_grad_norm: 1.0
flow_shape: [50, 30]

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

optimizer:
  learning_rate: 1e-4
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1e-2
  adam_epsilon: 1e-08

dataset:
  _target_: im2flow2act.flow_generation.dataloader.animateflow_mimicgen_3d_dataset.AnimateFlowMimicgen3DDataset
  data_path: "/data/yuanhong/mimicgen_data/core_datasets/coffee/demo_src_coffee_task_D1/demo_3d.hdf5"
  diff_flow: True
  flow_resize_length: 50

evaluation:
  eval_frequency: 50
  num_samples: 4
  num_inference_steps: 25
  guidance_scale: 8.

uni3d:
  pretrained_pc: ""
  pc_feat_dim: 1024
  embed_dim: 1024
  num_group: 512
  group_size: 64
  pc_encoder_dim: 512
  pc_model: "eva02_large_patch14_448"
  drop_path_rate: 0.0
  patch_dropout: 0.0
  npoints: 8000
  ckpt_path: "/home/yuanhong/Documents/Uni3D/checkpoints/model.pt"